"""initial schema

Revision ID: 40748db8885f
Revises: 
Create Date: 2026-06-10 11:58:32.314255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40748db8885f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escritorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escritorio_id', sa.Integer(), nullable=True),
    sa.Column('ator', sa.String(length=100), nullable=False),
    sa.Column('acao', sa.String(length=100), nullable=False),
    sa.Column('entidade', sa.String(length=50), nullable=True),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('detalhe', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['escritorio_id'], ['escritorio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escritorio_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['escritorio_id'], ['escritorio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escritorio_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('oab', sa.String(length=20), nullable=True),
    sa.Column('oab_uf', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['escritorio_id'], ['escritorio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuario_oab'), 'usuario', ['oab'], unique=False)
    op.create_table('credencial_assinatura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('provedor', sa.String(length=50), nullable=False),
    sa.Column('referencia_vault', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escritorio_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('classe', sa.String(length=255), nullable=True),
    sa.Column('tribunal', sa.String(length=50), nullable=True),
    sa.Column('orgao_julgador', sa.String(length=255), nullable=True),
    sa.Column('sistema', sa.String(length=50), nullable=True),
    sa.Column('data_ajuizamento', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['escritorio_id'], ['escritorio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('escritorio_id', 'numero', name='uq_processo_numero')
    )
    op.create_index(op.f('ix_processo_numero'), 'processo', ['numero'], unique=False)
    op.create_table('andamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processo_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('data', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['processo_id'], ['processo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intimacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processo_id', sa.Integer(), nullable=True),
    sa.Column('fonte', sa.String(length=20), nullable=False),
    sa.Column('fonte_id', sa.String(length=64), nullable=False),
    sa.Column('numero_processo', sa.String(length=30), nullable=True),
    sa.Column('tribunal', sa.String(length=50), nullable=True),
    sa.Column('tipo_comunicacao', sa.String(length=100), nullable=True),
    sa.Column('teor', sa.Text(), nullable=True),
    sa.Column('data_disponibilizacao', sa.Date(), nullable=True),
    sa.Column('data_publicacao', sa.Date(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['processo_id'], ['processo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fonte', 'fonte_id', name='uq_intimacao_fonte')
    )
    op.create_index(op.f('ix_intimacao_numero_processo'), 'intimacao', ['numero_processo'], unique=False)
    op.create_table('prazo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processo_id', sa.Integer(), nullable=True),
    sa.Column('intimacao_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('dias', sa.Integer(), nullable=False),
    sa.Column('dias_uteis', sa.Boolean(), nullable=False),
    sa.Column('data_fatal', sa.Date(), nullable=False),
    sa.Column('cumprido', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intimacao_id'], ['intimacao.id'], ),
    sa.ForeignKeyConstraint(['processo_id'], ['processo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peticao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processo_id', sa.Integer(), nullable=False),
    sa.Column('prazo_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('aprovada_por', sa.Integer(), nullable=True),
    sa.Column('protocolada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aprovada_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['prazo_id'], ['prazo.id'], ),
    sa.ForeignKeyConstraint(['processo_id'], ['processo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processo_id', sa.Integer(), nullable=True),
    sa.Column('peticao_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('uri', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['peticao_id'], ['peticao.id'], ),
    sa.ForeignKeyConstraint(['processo_id'], ['processo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documento')
    op.drop_table('peticao')
    op.drop_table('prazo')
    op.drop_index(op.f('ix_intimacao_numero_processo'), table_name='intimacao')
    op.drop_table('intimacao')
    op.drop_table('andamento')
    op.drop_index(op.f('ix_processo_numero'), table_name='processo')
    op.drop_table('processo')
    op.drop_table('credencial_assinatura')
    op.drop_index(op.f('ix_usuario_oab'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('cliente')
    op.drop_table('audit_log')
    op.drop_table('escritorio')
    # ### end Alembic commands ###
